### ISSUE TITLE
Several Questions When Trying to Reproduce

### ISSUE THREAD

**Issue by xorange** [jonhoare/git-merge-bug-demo#1]
First of all thanks for your demo.

Many have encountered code lost after git merge during collaboration. And it's hard to tell whether it's caused by human's mistake or tool's. I'm trying to learn git-merge and try to reproduce such a scene. Your demo provides a good foundation so thank you.

Back to demo. I've seen 2 mistakes in history:

1. 9fc23 + 813cf => 3c9d22

Error: Extra line "Feature1_Text1"
```
Initial Text
More text
Going to add some more text
Feature2 text in here
(+813cf)Feature4 text here
(+813cf)Feature3 text
(!)Feature1_Text1
(+813cf)Using Feature6
(!)Feature1_Text1
(+9fc23)Feature7
```

2. 1e6c8 + 40016 => d3410

Error: Lost content "Feature7"
```
Initial Text
More text
Going to add some more text
Feature2 text in here
Feature4 text here
Feature3 text
Feature1_Text1
(+40016)Using Feature6
(+40016)Feature1_Text1
(!-40016)Feature7
(+1e6c8)Featrue8
```

We know Git uses a (recursive) 3-way merge(diff3), and Using `git merge-base <commit1> <commit2>` we could learn about the common ancestor in merge.

I have several questions after I tried to do the merge myself and tried to reproduce the same history. I'll explain separately.

**Comment by xorange** [comment]
1. 9fc23 + 813cf => 3c9d22

`git merge-base 9fc23 813cf` gives `18c45`, that is:

(all are Initial.txt)

18c45
```
Initial Text
More text
Going to add some more text
Feature2 text in here
Feature1_Text1
```

9fc23:
```
Initial Text
More text
Going to add some more text
Feature2 text in here
Feature1_Text1
(+)Feature7
```

813cf
```
Initial Text
More text
Going to add some more text
Feature2 text in here
(+)Feature4 text here
(+)Feature3 text
Feature1_Text1
(+)Using Feature6
```

When I tried to reproduce the merge:
``` shell
$ git branch testmerge1 9fc23
$ git checkout -b testmerge2 813cf
$ git merge testmerge1
```

I got an merge conflict:
```
 $ git diff
diff --cc Initial.txt
index 029f1f0,23f103a..0000000
--- a/Initial.txt
+++ b/Initial.txt
@@@ -2,7 -2,5 +2,12 @@@ Initial Tex
  More text
  Going to add some more text
  Feature2 text in here
++<<<<<<< HEAD
 +Feature4 text here
 +Feature3 text
  Feature1_Text1
- Using Feature6
 -Feature7
++Using Feature6
++=======
++Feature1_Text1
++Feature7
++>>>>>>> testmerge1
```

I think the conflicts seemed correctly tell what's right, each side holds the correct modification from each merge branch.

And I cannot reproduce what the demo gives me.

**Comment by xorange** [comment]
Similarly, 1e6c8 + 40016 => d3410

```
git branch testmerge1 1e6c8
git checkout -b testmerge2 40016
git merge testmerge1
```

Results in conflict:
```
 $ git diff
diff --cc Initial.txt
index 213b723,1f941a8..0000000
--- a/Initial.txt
+++ b/Initial.txt
@@@ -5,6 -5,4 +5,10 @@@ Feature2 text in her
  Feature4 text here
  Feature3 text
  Feature1_Text1
 -Featrue8
++<<<<<<< HEAD
 +Using Feature6
 +Feature1_Text1
- Feature7
++Feature7
++=======
++Featrue8
++>>>>>>> testmerge1
```

Which are as expected from common ancestor `374c3`

**Comment by xorange** [comment]
So my questions go:

1. Do I correctly solve the demo's question?
2. How to reproduce same history? What's the workflow used here?

Thanks

**Comment by xorange** [comment]
FYI

```
* 315fa (1 year, 4 months ago) Updated readme [Jon Hoare] (HEAD -> master, origin/master, origin/HEAD)
* f2a6d (1 year, 4 months ago) Added Readme [Jon Hoare]
* 66f89 (1 year, 4 months ago) Fixed Typo [Jon Hoare]
*  ! d3410 (1 year, 4 months ago) Merge branch 'master' into feature/FEAT_8 [Jon Hoare]
|\  
| *   40016 (1 year, 4 months ago) Merge branch 'master' into bugfix/BUG1 [Jon Hoare]
| |\  
| | *  ! 3c9d2 (1 year, 4 months ago) Merge branch 'master' into feature/FEAT_7 [Jon Hoare]
| | |\  
| | | *   813cf (1 year, 4 months ago) Merge branch 'master' into feature/FEAT_6 [Jon Hoare]
| | | |\  
| | | * | 99807 (1 year, 4 months ago) Using Feature6 in Initial.txt [Jon Hoare]
| | | * | 6517a (1 year, 4 months ago) Starting work on Feature 6 [Jon Hoare]
| | * | | (+Feature 7) 9fc23 (1 year, 4 months ago) Added Feature 7 to Initial.txt [Jon Hoare]
| * | | | b4ce4 (1 year, 4 months ago) Fixed a bug from Feature4 [Jon Hoare]
| |/ / /  
| * | | e693c (1 year, 4 months ago) Merge commit '18c457f' into feature/FEAT_7 [Jon Hoare]
| |\| | 
| * | | 04a2e (1 year, 4 months ago) More work [Jon Hoare]
| * | | e951e (1 year, 4 months ago) Working on feature 7 [Jon Hoare]
* | | | 1e6c8 (1 year, 4 months ago) Added feature8 to Initial.txt [Jon Hoare]
* | | | 8ea36 (1 year, 4 months ago) Added new file for feature8 [Jon Hoare]
* | | | 57d52 (1 year, 4 months ago) Fixed a Bug found in Feature 4 [Jon Hoare]
| |_|/  
|/| |   
* | |   374c3 (1 year, 4 months ago) Merge branch 'master' into feature/FEAT_5 [Jon Hoare]
|\ \ \  
| * \ \   54a5a (1 year, 4 months ago) Merge branch 'master' into feature/FEAT_1 [Jon Hoare]
| |\ \ \  
| | * \ \   88c99 (1 year, 4 months ago) Merge branch 'master' into feature/FEAT3 [Jon Hoare]
| | |\ \ \  
| | | * | | 7406b (1 year, 4 months ago) More WIP [Jon Hoare]
| | | * | | 0a687 (1 year, 4 months ago) WIP [Jon Hoare]
| | | * | | ce6ab (1 year, 4 months ago) Added feauture4 text here [Jon Hoare]
| | * | | | 6f0f1 (1 year, 4 months ago) Added feature3 text [Jon Hoare]
| | |/ / /  
| * | | | 44589 (1 year, 4 months ago) More WIP for feature1 [Jon Hoare]
* | | | | d88b4 (1 year, 4 months ago) More commits after merging from master [Jon Hoare]
| |_|_|/  
|/| | |   
* | | | 18c45 (1 year, 4 months ago) Merge commit '8bef5a3' into feature/FEAT_5 [Jon Hoare]
|\| | | 
| * | | 8bef5 (1 year, 4 months ago) Merge branch 'master' into feature/FEAT_1 [Jon Hoare]
| |\| | 
| | * | 8a7d2 (1 year, 4 months ago) Added to initial.txt [Jon Hoare]
| | * | 38fef (1 year, 4 months ago) Added Feature2 Text 2 [Jon Hoare]
| | * | cb365 (1 year, 4 months ago) Added initial Feature2 Text [Jon Hoare]
| * | | 97307 (1 year, 4 months ago) Added Feature1 Text2 [Jon Hoare]
| * | | d0563 (1 year, 4 months ago) Added a feature1 file [Jon Hoare]
| * | | 67ca7 (1 year, 4 months ago) Added feature text 1 [Jon Hoare]
| |/ /  
| * / 81a44 (1 year, 4 months ago) Adding some more text [Jon Hoare]
| |/  
* | 00281 (1 year, 4 months ago) Added More changes [Jon Hoare]
* | 123a4 (1 year, 4 months ago) Initial [Jon Hoare]
|/  
* 2efd6 (1 year, 4 months ago) Added some more text here [Jon Hoare]
* ca56a (1 year, 4 months ago) Initial Text [Jon Hoare]
```

**Comment by jonhoare** [comment]
Hey, thanks for the detailed feedback and questions. To be honest with you, it was such a long time ago, I could not tell you exactly what happened and when. I completely forgot these repositories even existed as I created them for some team members I was working with to exaggerate a point I was making about different merge strategies.

All I remember doing for this example was making changes in different branches using `git merge` to merge backwards and forwards between branches to simulate what I have seen with larger teams before.

But this has exactly highlighted my point, although I never really raised that point in the readme, that it is incredibly difficult to look back through a history like this and work out what happened, when, by who, and how it happened, when you are merging backwards and forwards between branches. 

This repo is part of a few other demo scenarios that show different merging/branching strategies, and how they all differ and hopefully some, over others make it easier to read the history and understand what happened, how, when and by who.

https://github.com/jonhoare/git-merge-no-ff-bug-demo
https://github.com/jonhoare/git-rebase-bug-demo

A point that I was trying to make for my team members using these examples was that it makes much more sense to use a `rebase` to get changes from your base branch and then use `merge` to merge your change back onto your base branch, as this gives you a much cleaner, linear view of what happened, and a chance to fix your conflicts in stages.

**Comment by xorange** [comment]
Thanks for you reply.

I'm trying to do the exact same thing, to illustrate to my colleagues about how to use Git wisely instead of tripping on it from time to time.

I get your idea, along with several popular git workflows. 

I just finish reading [the Formal Investigation of Diff3](https://www.cis.upenn.edu/~bcpierce/papers/diff3-short.pdf). I'm gonna settle with the idea that "merge and rebase are both technically trustworthy" and "some ghost event of code vanishing  during git-merge is believed to be a mistake external to git."

This repo still helps me a lot and Thanks again.
